import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Blackpig Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row" style={{ alignItems: "center" }}>
        <div className="col-lg-5">
          <p className={styles.mainTitle}>
            Happy Birthday <br />
            My Baby <br /> Black Pig
          </p>
          <p className={styles.subParagraph}>
            May this day be filled with many beautiful <br /> gifts, but above
            all with much affection and <br /> the immense love I feel for you I
            wish you the <br /> best on your birthday.
          </p>
          <button className={styles.btnTour + " btn"}>Get a Tour</button>
        </div>
        <div className="col-lg-7">
          <img src="/birthday.png" className={styles.img} />
        </div>
      </div>
    </div>
  );
}
